{% set name = "tblite" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tblite/tblite/releases/download/v{{ version }}/tblite-{{ version }}.tar.xz
  sha256: e8a70b72ed0a0db0621c7958c63667a9cd008c97c868a4a417ff1bc262052ea8
  patches:
    - find-lib.patch
    - set-stat.patch
    - fix-tblite-table-set-value.patch
    - print.patch

build:
  number: 2

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - dftd4 >=3.4,<4
    - libblas
    - liblapack
    - mctc-lib >=0.3
    - pkg-config
    - simple-dftd3 >=0.6,<2
    - toml-f >=0.4.3

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - pkg-config {{ name }} --modversion
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/include/{{ name }}.h  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_BIN%\\lib{{ name }}-0.dll exit 1  # [win]

about:
  home: https://github.com/tblite/tblite
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Light-weight tight-binding framework
  doc_url: https://tblite.readthedocs.io
  dev_url: https://github.com/tblite/tblite

extra:
  recipe-maintainers:
    - yuzie007
    - awvwgk
